services:
  mysql:
    image: mysql:8.4
    container_name: chatapp-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - chatapp-mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: chatapp-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  chatapp-mysql-data: