services:
  mysql:
    image: mysql:8.4
    container_name: chatapp-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - chatapp-mysql-data:/var/lib/mysql

volumes:
  chatapp-mysql-data: