spring.application.name=ChatApp

spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/chatapp}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.defer-datasource-initialization=true

# MAIL (MailHog)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.from=${MAIL_FROM:noreply@chatapp.com}
